### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Pubstars** [tazeat/AutoFullscreen#1]
Hey,

First off thank you for the great extension!  I had a quick question, would it be possible to add an option to disable the right click context menu so users cannot select view source etc?

Regards

**Comment by tazeat** [comment]
I would say that's outside the scope of this plugin, but it's certainly possible.

Perhaps unzip this and see how they capture the right click even and instead of allowing it you return false or similar instead to disable it.
https://addons.mozilla.org/en-US/firefox/addon/enable-rightclick-and-copy/

**Comment by Pubstars** [comment]
Ok thanks for the swift reply and suggestion.
